[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build:prod']

[start]
cmd = 'node dist/server.cjs'

[deploy]
startCommand = 'node dist/server.cjs'
restartPolicyType = 'ON_FAILURE'
restartPolicyMaxRetries = 10 