[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build:prod']

[start]
cmd = 'npm run start'

[variables]
NPM_CONFIG_PRODUCTION = "false" 